name: build
on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        run: |
          docker build -t demo-image .
      - name: List docker images
        run: |
          docker images  

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'demo-image'
          format: 'table'
          vuln-type: 'os,library'
          
          
      - name: List docker images tag
        run: |
          docker tag demo-image:latest demo-image:tag1
          docker images

